pipeline{
    agent any
     
     stages{
       stage('build'){
        steps{
            echo "My name is billa"
        }
       }
       stage('test'){
        steps{
            echo "My life is bad"
        }
       }
       stage('deploy'){
        steps{
            echo "my location karaikal"
        }
       }

     }
}
